[package]
name = "casbin"
version = "0.1.2"
authors = ["Joey <joey.xf@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An authorization library that supports access control models like ACL, RBAC, ABAC."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
rhai = "0.9.1"
ip_network = "0.3.4"
