[package]
name = "casbin-rs"
version = "0.1.0"
authors = ["Joey <joey.xf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rhai = "0.7"
ip_network = "0.3.4"
diesel = { version = "1.4.2", features = ["r2d2", "postgres"], optional = true }

[features]
default = ["postgres"]

postgres = ["diesel"]
